package racegrid.api.model;

public enum RacegridError {
    GAME_NOT_FOUND,
    USER_NOT_FOUND,
    USER_IN_GAME,
    INVALID_MOVE,
    NOT_PLAYERS_TURN,
    INTERNAL,
    GAME_ALREADY_RUNNING,
    GAME_NOT_RUNNING,
    AUTHENTICATION_ERROR,
    CAN_NOT_START_GAME,
    LOBBY_NOT_FOUND,
}
